### ISSUE TITLE
HTML minification failed when you use '<3'

### ISSUE THREAD

**Issue by yangwao** [nuxt-community/starter-template#28]
⫸  vue init nuxt-community/starter-template my-project5

? Project name my-project5
? Project description Nuxt.js project
? Author Matej Nemcek <ybdaba@gmail.com>
⫸  cd my-project5/
⫸  npm i
⫸  nano pages/index.vue
add there & save
```
<h2 class="subtitle">
        Nuxt.js project <3
      </h2>
```
important is `<3`
```
⫸  npm run generate

> my-project5@1.0.0 generate /Users/wao/Lab/my-project5
> nuxt generate

  nuxt:generate Generating... +0ms
  nuxt:build App root: /Users/wao/Lab/my-project5 +11ms
  nuxt:build Generating /Users/wao/Lab/my-project5/.nuxt files... +1ms
  nuxt:build Generating files... +4ms
  nuxt:build Generating routes... +6ms
  nuxt:build Building files... +32ms
Build completed in 9.81s

Hash: 4a239bda8af56836cc08
Version: webpack 3.4.1
Time: 9816ms
                                    Asset       Size  Chunks             Chunk Names
1.nuxt.bundle.5eafb0451c075ef76c54.js.map    1.69 kB       1  [emitted]  layouts/default
    0.nuxt.bundle.0a62bbba6a9a5b4d140a.js    7.79 kB       0  [emitted]  pages/index
    vendor.bundle.a4a5870e2d91a576147c.js     145 kB       2  [emitted]  vendor
      nuxt.bundle.898b0a05415ed638f08d.js    25.3 kB       3  [emitted]  app
         manifest.4a239bda8af56836cc08.js    1.54 kB       4  [emitted]  manifest
0.nuxt.bundle.0a62bbba6a9a5b4d140a.js.map    3.76 kB       0  [emitted]  pages/index
    1.nuxt.bundle.5eafb0451c075ef76c54.js    2.95 kB       1  [emitted]  layouts/default
vendor.bundle.a4a5870e2d91a576147c.js.map     231 kB       2  [emitted]  vendor
  nuxt.bundle.898b0a05415ed638f08d.js.map    40.5 kB       3  [emitted]  app
     manifest.4a239bda8af56836cc08.js.map    2.81 kB       4  [emitted]  manifest
                           index.ssr.html  132 bytes          [emitted]
                           index.spa.html  398 bytes          [emitted]
             vue-ssr-client-manifest.json    7.45 kB          [emitted]
Hash: 33154686e9f0a9170b51
Version: webpack 3.4.1
Time: 9800ms
             Asset    Size  Chunks             Chunk Names
server-bundle.json  242 kB          [emitted]
  nuxt:generate Destination folder cleaned +10s
  nuxt:generate Static & build files copied +15ms
Generating routes
  nuxt:render Rendering url / +4ms
  nuxt:generate Generate file: /index.html +118ms
  nuxt:generate HTML Files generated in 10.2s +0ms
==== Error report ====
Route: '/'
Error: HTML minification failed. Make sure the route generates valid HTML. Failed HTML:
 <!DOCTYPE html>
<html data-n-head-ssr data-n-head="">
  <head>
    <meta data-n-head="true" charset="utf-8"/><meta data-n-head="true" name="viewport" content="width=device-width, initial-scale=1"/><meta data-n-head="true" data-hid="description" name="description" content="Nuxt.js project"/><title data-n-head="true">my-project5</title><link data-n-head="true" rel="icon" type="image/x-icon" href="/favicon.ico"/><link rel="preload" href="/_nuxt/manifest.4a239bda8af56836cc08.js" as="script"><link rel="preload" href="/_nuxt/vendor.bundle.a4a5870e2d91a576147c.js" as="script"><link rel="preload" href="/_nuxt/nuxt.bundle.898b0a05415ed638f08d.js" as="script"><link rel="preload" href="/_nuxt/1.nuxt.bundle.5eafb0451c075ef76c54.js" as="script"><link rel="preload" href="/_nuxt/0.nuxt.bundle.0a62bbba6a9a5b4d140a.js" as="script"><style data-vue-ssr-id="49020bdc:0 01b78770:0 2fbab843:0 c8fee4cc:0">.progress[data-v-3bea9706]{position:fixed;top:0;left:0;right:0;height:2px;width:0;-webkit-transition:width .2s,opacity .4s;-o-transition:width .2s,opacity .4s;transition:width .2s,opacity .4s;opacity:1;background-color:#efc14e;z-index:999999}
html{font-family:Source Sans Pro,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif;font-size:16px;word-spacing:1px;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased}*,:after,:before,html{-webkit-box-sizing:border-box;box-sizing:border-box}*,:after,:before{margin:0}.button--green{display:inline-block;border-radius:4px;border:1px solid #3b8070;color:#3b8070;text-decoration:none;padding:10px 30px}.button--green:hover{color:#fff;background-color:#3b8070}.button--grey{display:inline-block;border-radius:4px;border:1px solid #35495e;color:#35495e;text-decoration:none;padding:10px 30px;margin-left:15px}.button--grey:hover{color:#fff;background-color:#35495e}
.container{min-height:100vh;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;text-align:center}.title{font-family:Quicksand,Source Sans Pro,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif;display:block;font-weight:300;font-size:100px;color:#35495e;letter-spacing:1px}.subtitle{font-weight:300;font-size:42px;color:#526488;word-spacing:5px;padding-bottom:15px}.links{padding-top:15px}
.VueToNuxtLogo{display:inline-block;-webkit-animation:turn 2s linear forwards 1s;animation:turn 2s linear forwards 1s;-webkit-transform:rotateX(180deg);transform:rotateX(180deg);position:relative;overflow:hidden;height:180px;width:245px}.Triangle{position:absolute;top:0;left:0;width:0;height:0}.Triangle--one{border-left:105px solid transparent;border-right:105px solid transparent;border-bottom:180px solid #41b883}.Triangle--two{top:30px;border-left:87.5px solid transparent;border-right:87.5px solid transparent;border-bottom:150px solid #3b8070}.Triangle--three,.Triangle--two{left:35px;-webkit-animation:goright .5s linear forwards 3.5s;animation:goright .5s linear forwards 3.5s}.Triangle--three{top:60px;border-left:70px solid transparent;border-right:70px solid transparent;border-bottom:120px solid #35495e}.Triangle--four{top:120px;left:70px;-webkit-animation:godown .5s linear forwards 3s;animation:godown .5s linear forwards 3s;border-left:35px solid transparent;border-right:35px solid transparent;border-bottom:60px solid #fff}@-webkit-keyframes turn{to{-webkit-transform:rotateX(0deg);transform:rotateX(0deg)}}@keyframes turn{to{-webkit-transform:rotateX(0deg);transform:rotateX(0deg)}}@-webkit-keyframes godown{to{top:180px}}@keyframes godown{to{top:180px}}@-webkit-keyframes goright{to{left:70px}}@keyframes goright{to{left:70px}}</style>
  </head>
  <body data-n-head="">
    <div id="__nuxt" data-server-rendered="true"><div class="progress" style="width:0%;height:2px;background-color:#3B8070;opacity:0;" data-v-3bea9706></div><div><section class="container"><div><div class="VueToNuxtLogo"><div class="Triangle Triangle--two"></div><div class="Triangle Triangle--one"></div><div class="Triangle Triangle--three"></div><div class="Triangle Triangle--four"></div></div><h1 class="title">
      my-project5
    </h1><h2 class="subtitle">
      Nuxt.js project <3
    </h2><div class="links"><a href="https://nuxtjs.org/" target="_blank" class="button--green">Documentation</a><a href="https://github.com/nuxt/nuxt.js" target="_blank" class="button--grey">GitHub</a></div></div></section></div></div><script type="text/javascript">window.__NUXT__={"layout":"default","data":[{}],"error":null,"state":{},"serverRendered":true};</script><script src="/_nuxt/manifest.4a239bda8af56836cc08.js" defer></script><script src="/_nuxt/1.nuxt.bundle.5eafb0451c075ef76c54.js" defer></script><script src="/_nuxt/0.nuxt.bundle.0a62bbba6a9a5b4d140a.js" defer></script><script src="/_nuxt/vendor.bundle.a4a5870e2d91a576147c.js" defer></script><script src="/_nuxt/nuxt.bundle.898b0a05415ed638f08d.js" defer></script>
  </body>
</html>

    at Generator._callee4$ (/Users/wao/Lab/my-project5/node_modules/nuxt/lib/builder/generator.js:153:27)
    at tryCatch (/Users/wao/Lab/my-project5/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/wao/Lab/my-project5/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/wao/Lab/my-project5/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/wao/Lab/my-project5/node_modules/nuxt/dist/nuxt.js:852:30)
    at /Users/wao/Lab/my-project5/node_modules/nuxt/dist/nuxt.js:863:13
  nuxt:generate Generate done +17ms
```
nuxt version is 1.0.0-rc3

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c18">#c18</a>)</em></sub></div>

**Comment by atinux** [comment]
Hi @yangwao 

You need to use the valid HTML character for this `&lt;`, so in your page:

```html
<h2 class="subtitle">
  Nuxt.js project &lt;3
</h2>
```
