### ISSUE TITLE
error in start template

### ISSUE THREAD

**Issue by wi-cuckoo** [nuxt-community/starter-template#34]
just as normal step to init my project
$ vue init nuxt-community/starter-template test-nuxt
$ cd test-nuxt
$ npm install
$ npm run dev

then the error is:
```
> test-nuxt@1.0.0 dev /home/wi/bin/test-nuxt
> nuxt

  nuxt:build App root: /home/wi/bin/test-nuxt +0ms
  nuxt:build Generating /home/wi/bin/test-nuxt/.nuxt files... +1ms
  nuxt:build Generating files... +7ms
  nuxt:build Generating routes... +5ms
  nuxt:build Building files... +25ms
  nuxt:build Adding webpack middleware... +135ms
  build [==                  ] 10%Error: watch /home/wi/bin/test-nuxt/pages ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1297:19)
    at Object.fs.watch (fs.js:1322:11)
    at createFsWatchInstance (/home/wi/bin/test-nuxt/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/wi/bin/test-nuxt/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/wi/bin/test-nuxt/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/wi/bin/test-nuxt/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/wi/bin/test-nuxt/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/wi/bin/test-nuxt/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:111:15)
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c23">#c23</a>)</em></sub></div>

**Comment by ghengeveld** [comment]
Your harddisk seems to be full, that's what ENOSPC means.

**Comment by wi-cuckoo** [comment]
@ghengeveld Yeah, that's the means. But I check my disk, and not full.

**Comment by NicoPennec** [comment]
it's a common issue on amount of inotify watchers on Linux.

follow these guides to fix your OS config:
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details
https://stackoverflow.com/questions/22475849/node-js-error-enospc
