### ISSUE TITLE
when I run npm run dev show an error

### ISSUE THREAD

**Issue by feivorid** [nuxt-community/starter-template#37]
`Error: listen EADDRNOTAVAIL 172.0.0.1:3000`
    `at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1243:19)
    at listenInCluster (net.js:1307:12)
    at doListen (net.js:1432:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:10)`

what should I do ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c24">#c24</a>)</em></sub></div>

**Comment by owm111** [comment]
From my experience, `EADDRNOTAVAIL` means that something is already using port 3000, so you can either close what is taking up that port or configure Nuxt to use a different one.
