### ISSUE TITLE
error threw on run dev or build

### ISSUE THREAD

**Issue by herbat73** [nuxt-community/starter-template#49]
It is just a suggestion to add info to the requirements list : node > 8.1.1

It does not work on
npm : 5.6.0
vue: 2.9.2
node: 7.10
Win: 10

```
const glob = promisify(Glob)
             ^

TypeError: promisify is not a function
    at Object.<anonymous> (C:\Users\AdamSurface\Source\Repos\ninext\node_modules\nuxt\lib\builder\builder.js:32:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\AdamSurface\Source\Repos\ninext\node_modules\nuxt\lib\builder\index.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ninext@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ninext@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c36">#c36</a>)</em></sub></div>

**Comment by atinux** [comment]
You need to use node >= 8 to use Nuxt.js now
