### ISSUE TITLE
when I exec the command line 'npm run dev', it occurs some error.My vue version is 2.8.3 and node version is v7.5.0

### ISSUE THREAD

**Issue by ghost** [nuxt-community/starter-template#56]
node_modules\_nuxt@1.3.0@nuxt\lib\core\module.js:14
async ready() {
        ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\learning\vue\my-nuxt-project\node_modules\_nuxt@1.3.0@nuxt\lib\core\index.js:2:16)
    at Module._compile (module.js:571:32)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c32">#c32</a>)</em></sub></div>

**Comment by ghost** [comment]
I have solved this problem because node@v7.5.0 is incompatible with nuxt@^1.0.0, expected node@>=8.0.0 (node@version=7.5.0 => nuxt@0.10.6 )
