### ISSUE TITLE
when I run npm run dev show an error

### ISSUE THREAD

**Issue by erbing** [nuxt-community/starter-template#61]
```node
E:\github\nuxtJs\node_modules\nuxt\lib\core\middleware\nuxt.js:72
      const policies = this.options.render.csp.policies ? {...this.options.rende
r.csp.policies} : null
                                                           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\github\nuxtJs\node_modules\nuxt\lib\core\renderer.
js:19:24)
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c39">#c39</a>)</em></sub></div>

**Comment by erbing** [comment]
```node

E:\github\nuxtJs>node -v
v8.2.0

E:\github\nuxtJs>npm -v
5.3.0

```

**Comment by dokudoki** [comment]
I have the same issue.

UPDATE: @erbing  Seems like you need node version 8.6.0 or higher.

**Comment by erbing** [comment]
WOW,  it really worked out, thx !!!

**Comment by erbing** [comment]
@tyuwan
