### ISSUE TITLE
Error during running npm run dev in project

### ISSUE THREAD

**Issue by glenlzk** [nuxt-community/starter-template#62]
I started my first Nuxt project via:
         $ vue init nuxt-community/starter-template nuxt-demo

then install the dependencies:
and launch the project with: 
        $ npm run dev

but the application can't get started with the following errors:

D:\demo\nuxt-ssr-demo\node_modules\nuxt\lib\core\module.js:14
  async ready() {
        ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\demo\nuxt-ssr-demo\node_modules\nuxt\lib\core\inde
x.js:2:16)
    at Module._compile (module.js:571:32)

I don't know why. please help me fixed this problem, thx so much!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c40">#c40</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
@glenlzk try to upgrade your node.js install to the latest node 8 LTS version => https://nodejs.org/en/

**Comment by glenlzk** [comment]
@NicoPennec You are very nice! Thanks a lot.
