### ISSUE TITLE
I get  ERROR  Failed to compile with 5 errors after clear installation.                                                                                 02:06:18

### ISSUE THREAD

**Issue by AchillesKal** [nuxt-community/starter-template#69]
It's the first time I try to install nuxt, I just followed the docs:

- vue init nuxt-community/starter-template test
- cd test
- yarn install
- yarn run dev

My node version is v8.4.0

I get this error:
```
 ERROR  Failed to compile with 5 errors                                                                                               02:20:24

 error  in ./.nuxt/components/nuxt-error.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:7051:13)
    at formatWithCursor (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:10370:12)
    at /home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31115:15
    at Object.format (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31134:12)
    at Object.module.exports (/home/achilleskal/Projects/vue/test/node_modules/vue-loader/lib/template-compiler/index.js:80:23)

 @ ./.nuxt/components/nuxt-error.vue 11:0-379
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

 error  in ./.nuxt/components/nuxt-loading.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:7051:13)
    at formatWithCursor (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:10370:12)
    at /home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31115:15
    at Object.format (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31134:12)
    at Object.module.exports (/home/achilleskal/Projects/vue/test/node_modules/vue-loader/lib/template-compiler/index.js:80:23)

 @ ./.nuxt/components/nuxt-loading.vue 11:0-381
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

 error  in ./pages/index.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:7051:13)
    at formatWithCursor (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:10370:12)
    at /home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31115:15
    at Object.format (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31134:12)
    at Object.module.exports (/home/achilleskal/Projects/vue/test/node_modules/vue-loader/lib/template-compiler/index.js:80:23)

 @ ./pages/index.vue 11:0-368
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

 error  in ./layouts/default.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:7051:13)
    at formatWithCursor (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:10370:12)
    at /home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31115:15
    at Object.format (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31134:12)
    at Object.module.exports (/home/achilleskal/Projects/vue/test/node_modules/vue-loader/lib/template-compiler/index.js:80:23)

 @ ./layouts/default.vue 10:0-370
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

 error  in ./components/AppLogo.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:7051:13)
    at formatWithCursor (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:10370:12)
    at /home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31115:15
    at Object.format (/home/achilleskal/Projects/vue/test/node_modules/prettier/index.js:31134:12)
    at Object.module.exports (/home/achilleskal/Projects/vue/test/node_modules/vue-loader/lib/template-compiler/index.js:80:23)

 @ ./components/AppLogo.vue 10:0-370
 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["/home/achilleskal/Projects/vue/test/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c50">#c50</a>)</em></sub></div>

**Comment by brandonaaskov** [comment]
I'm seeing the exact same thing. I opened a bug report for this same issue you hit: https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c51

**Comment by warriorBrian** [comment]
I also have the same problem!!! There is this problem in all forums!!! @AchillesKal
