### ISSUE TITLE
events.js:183 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Awais-cb** [nuxt-community/starter-template#87]
just installed nuxt starter template with new project and just changes the title in nuxt.config.js re ran the dev server again and i am constanly getting this error why is that? i am using windows OS i have node > 8 installed

> > nuxt-warmup@1.0.0 dev C:\xampp\htdocs\nuxt-warmup
> > nuxt
> 
> [23:50:09] Building project
> [23:50:09] Builder initialized
> [23:50:09] Nuxt files generated
> [23:50:13] Compiling client
> [23:50:13] Compiling server
> [23:50:27] Compiled server in 14s
> [23:50:27] Compiled client in 15s
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE 127.0.0.1:3000
>     at Object._errnoException (util.js:1024:11)
>     at _exceptionWithHostPort (util.js:1046:20)
>     at Server.setupListenHandle [as _listen2] (net.js:1351:14)
>     at listenInCluster (net.js:1392:12)
>     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nuxt-warmup@1.0.0 dev: `nuxt`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nuxt-warmup@1.0.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Awais\AppData\Roaming\npm-cache\_logs\2018-10-27T18_50_27_670Z-debug.log
 

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/starter-template/issues/c59">#c59</a>)</em></sub></div>

**Comment by Awais-cb** [comment]
i had this issue on windows solved it using the commands below remember these commands will only work in cmd not in gitbash
this command will give you the process id of the process running on that specific port

> $ netstat -ano | find ":3000 "

this command will tell you which program is using this port

> $ tasklist /fi "pid eq {process-id}"

and this will kill that process

> $ taskkill /pid {process-id} /f

**Comment by Awais-cb** [comment]
or you can simply run task manager and kill node's process which is actually causing this error!
